export type AttachmentGroup = "steady-close" | "alert-close" | "steady-space" | "alert-space";

export type AttachmentType = {
  code: string;
  name: string;
  group: AttachmentGroup;
  tagline: string;
  tendency: string;
  summary: string;
  action: string;
  need: string;
  stress: string;
  partnerMoves: string[];
  selfMoves: string[];
  similar: string[];
};

export const ATTACHMENT_GROUPS: {
  id: AttachmentGroup;
  label: string;
  description: string;
}[] = [
  { id: "steady-close", label: "安稳靠近", description: "愿意亲近，对关系基本信任" },
  { id: "alert-close", label: "警觉靠近", description: "渴望亲近，也会紧盯关系信号" },
  { id: "steady-space", label: "安稳留白", description: "重视空间，但不把独立等同于疏远" },
  { id: "alert-space", label: "警觉留白", description: "既怕受伤，又担心彻底失去连接" },
];

export const TYPE_DIMENSIONS = [
  {
    key: "closeness",
    label: "亲密取向",
    left: "C 靠近",
    right: "I 留白",
    description: "需要连接时，是主动靠近，还是先保留空间。",
  },
  {
    key: "trust",
    label: "关系预期",
    left: "T 信任",
    right: "V 警觉",
    description: "面对不确定时，是默认关系稳定，还是优先扫描风险。",
  },
  {
    key: "conflict",
    label: "冲突动作",
    left: "D 直面",
    right: "W 缓冲",
    description: "出现分歧时，是当下说清，还是先暂停和降温。",
  },
  {
    key: "repair",
    label: "修复重心",
    left: "R 共建",
    right: "P 自保",
    description: "修复关系时，是优先共同解决，还是先恢复自己的安全感。",
  },
] as const;

export const ATTACHMENT_TYPES: AttachmentType[] = [
  {
    code: "CTDR",
    name: "稳定联结者",
    group: "steady-close",
    tagline: "把话说开，也把关系留住。",
    tendency: "接近安全型互动",
    summary: "愿意表达需求、承认分歧，也相信一次冲突不会自动摧毁关系。",
    action: "把问题摆到桌面上，同时确认彼此仍站在同一边。",
    need: "清楚、持续且有回应的合作感。",
    stress: "压力大时会加快解决节奏，容易低估对方需要缓冲的时间。",
    partnerMoves: ["直接说明你现在能谈多少", "给出明确的下一次沟通时间", "对方案之外的情绪也作回应"],
    selfMoves: ["先确认感受，再推进解决", "允许问题分两次谈完", "别把高效沟通变成替对方决定"],
    similar: ["CTWR", "ITDR", "CVDR"],
  },
  {
    code: "CTDP",
    name: "热心推进者",
    group: "steady-close",
    tagline: "喜欢就行动，卡住就处理。",
    tendency: "安全底色，带主动掌舵",
    summary: "对关系有信心，习惯用行动推进亲密，也倾向自己先把局面扛起来。",
    action: "通过安排、确认和解决问题，让关系保持向前。",
    need: "对方可见的投入，而不是口头上的“都可以”。",
    stress: "可能把照顾变成接管，把效率放在共同决定之前。",
    partnerMoves: ["主动承担一部分计划", "不同意时给出替代方案", "明确感谢具体付出"],
    selfMoves: ["在安排前先征求意见", "给对方主动靠近的空间", "区分负责与过度负责"],
    similar: ["CTDR", "ITDP", "CVDP"],
  },
  {
    code: "CTWR",
    name: "温柔缓冲者",
    group: "steady-close",
    tagline: "先让情绪落地，再把事情谈完。",
    tendency: "接近安全型互动",
    summary: "重视亲密与修复，不急着在情绪最高点争出结论。",
    action: "先降温、照顾感受，等双方能听见彼此时再恢复沟通。",
    need: "暂停以后仍会回来，而不是无限期搁置。",
    stress: "为了维持温和，可能推迟必要的边界表达。",
    partnerMoves: ["尊重暂停，但约定恢复时间", "不要把温和误解成没有立场", "用低压方式邀请其表达"],
    selfMoves: ["暂停时说清何时回来", "把不舒服说成具体事实", "温柔不等于取消自己的需求"],
    similar: ["CTDR", "CTWP", "ITWR"],
  },
  {
    code: "CTWP",
    name: "随和守候者",
    group: "steady-close",
    tagline: "关系很重要，我可以先让一步。",
    tendency: "安全底色，带和谐取向",
    summary: "相信关系总体可靠，愿意迁就和等待，但不总能及时说出自己的不满。",
    action: "维持气氛、降低摩擦，把自己的需求暂时放到后面。",
    need: "被主动询问，也被允许说“不”。",
    stress: "长期积累后可能突然失去耐心，令对方误以为毫无征兆。",
    partnerMoves: ["别只接受其“没事”", "用具体选项邀请真实偏好", "留意长期单向迁就"],
    selfMoves: ["在小事上练习表达偏好", "不舒服时尽早说两成", "别用沉默测试对方能否发现"],
    similar: ["CTWR", "ITWP", "CVWP"],
  },
  {
    code: "CVDR",
    name: "关系急救员",
    group: "alert-close",
    tagline: "发现温差，就立刻抢修。",
    tendency: "偏焦虑型互动",
    summary: "对关系变化很敏锐，愿意积极修复，但容易把普通波动当成紧急事故。",
    action: "快速定位异常、发起沟通，努力把关系拉回熟悉的温度。",
    need: "稳定回应和可预测的连接。",
    stress: "会连续解释、确认和追问，让对方感到没有喘息空间。",
    partnerMoves: ["先明确关系没有失联", "再说明需要多少时间", "按承诺回来继续沟通"],
    selfMoves: ["把一次确认限制为一个问题", "先区分事实与猜测", "等待期间回到自己的生活节奏"],
    similar: ["CVDP", "CTDR", "CVWR"],
  },
  {
    code: "CVDP",
    name: "确认追问者",
    group: "alert-close",
    tagline: "我要一个确定答案，现在。",
    tendency: "偏焦虑型互动",
    summary: "渴望明确承诺，遇到模糊信号时会用追问和推进保护自己。",
    action: "通过提高沟通强度，迫使不确定尽快变成结论。",
    need: "清晰边界、明确答复和言行一致。",
    stress: "容易把追问升级成审讯，或者用强硬语气掩盖害怕失去。",
    partnerMoves: ["少用模糊拖延", "给可执行而非敷衍的答复", "同时守住自己的沟通边界"],
    selfMoves: ["一次只解决一个问题", "用请求替代结论式指控", "接受有些答案需要观察而非逼问"],
    similar: ["CVDR", "IVDP", "CTDP"],
  },
  {
    code: "CVWR",
    name: "敏感调频者",
    group: "alert-close",
    tagline: "先读空气，再决定怎么靠近。",
    tendency: "焦虑与讨好倾向",
    summary: "擅长感知细微情绪，会不断调整自己以维持连接。",
    action: "观察语气和回复速度，降低自己的存在感，等待安全信号。",
    need: "不必靠猜就能获得的情绪信息。",
    stress: "可能过度解读细节，把对方的情绪都归因于自己。",
    partnerMoves: ["主动说明情绪与其是否有关", "拒绝时给出清晰边界", "肯定其无需完美配合"],
    selfMoves: ["先问，不替对方解释", "记录客观行为而非脑补", "保留不围绕关系运转的时间"],
    similar: ["CVWP", "CTWR", "IVWR"],
  },
  {
    code: "CVWP",
    name: "全天候守候者",
    group: "alert-close",
    tagline: "我先不打扰，但我一直在等。",
    tendency: "偏焦虑型互动",
    summary: "很需要连接，却担心表达需求会造成负担，于是把焦虑藏进等待与付出。",
    action: "压住直接追问，用持续关心和随叫随到换取关系确定性。",
    need: "无需靠过度付出才能获得的稳定回应。",
    stress: "表面安静，内在反复计数，最后可能用撤回付出来表达失望。",
    partnerMoves: ["别把随和当成没有需求", "主动确认关系安排", "避免只在需要帮助时出现"],
    selfMoves: ["直接说出最小可满足需求", "停止用付出交换猜测中的承诺", "观察对方是否也在主动"],
    similar: ["CVWR", "CTWP", "IVWP"],
  },
  {
    code: "ITDR",
    name: "理性协作者",
    group: "steady-space",
    tagline: "各自站稳，再一起解决。",
    tendency: "安全自主型互动",
    summary: "重视独立和直接沟通，愿意合作，但不把时刻黏在一起视为亲密证明。",
    action: "界定问题、交换信息，然后共同确定可执行方案。",
    need: "尊重空间、沟通有效、承诺可兑现。",
    stress: "可能快速进入分析模式，让需要情绪承接的人觉得被冷处理。",
    partnerMoves: ["把需求说具体", "给其思考时间", "提醒其先回应感受而非只给方案"],
    selfMoves: ["解决前先复述对方感受", "主动分享过程而非只报结论", "别把低频联系当成默认共识"],
    similar: ["CTDR", "ITDP", "ITWR"],
  },
  {
    code: "ITDP",
    name: "边界维护者",
    group: "steady-space",
    tagline: "亲密可以，边界也要写清。",
    tendency: "自主型互动",
    summary: "愿意进入关系，同时对时间、责任和私人空间有清晰要求。",
    action: "通过规则和边界避免关系侵占各自生活。",
    need: "选择权，以及边界被认真对待。",
    stress: "边界表达可能变硬，让协商听起来像单方面通知。",
    partnerMoves: ["先确认边界再谈调整", "不要用内疚推动让步", "提出对等且具体的需求"],
    selfMoves: ["说明边界背后的需要", "给协商留下范围", "定期确认旧规则是否仍适用"],
    similar: ["ITDR", "CTDP", "IVDP"],
  },
  {
    code: "ITWR",
    name: "松弛独行者",
    group: "steady-space",
    tagline: "不急着黏紧，也不会突然消失。",
    tendency: "安全自主型互动",
    summary: "习惯保留个人节奏，冲突时会先整理自己，但通常愿意按约定回来。",
    action: "暂时退开、恢复秩序，再以较低情绪强度重新连接。",
    need: "可呼吸的关系节奏和可信的回归通道。",
    stress: "暂停时间过长时，对方可能无法判断这是整理还是疏远。",
    partnerMoves: ["允许暂停并约定时间", "避免连续轰炸信息", "恢复沟通时直接谈主题"],
    selfMoves: ["离开前说清不是消失", "主动发起恢复沟通", "分享一点整理过程"],
    similar: ["ITWP", "CTWR", "ITDR"],
  },
  {
    code: "ITWP",
    name: "安静降温者",
    group: "steady-space",
    tagline: "先把自己安顿好，再看要不要谈。",
    tendency: "自主偏回避型互动",
    summary: "依靠自我调节处理压力，不喜欢在情绪高点暴露脆弱。",
    action: "减少互动、恢复个人节奏，用距离控制冲突强度。",
    need: "不被逼迫的思考空间，以及可选择的表达方式。",
    stress: "容易把暂时回避变成长期不处理，让问题失去入口。",
    partnerMoves: ["给空间但保留明确期限", "使用简短、具体的问题", "不把追击当成亲密证明"],
    selfMoves: ["至少确认已收到对方诉求", "给出恢复联系的时间", "练习表达需求而非只表达拒绝"],
    similar: ["ITWR", "CTWP", "IVWP"],
  },
  {
    code: "IVDR",
    name: "谨慎谈判者",
    group: "alert-space",
    tagline: "可以谈，但我要先确认不会吃亏。",
    tendency: "恐惧回避倾向",
    summary: "愿意面对问题，却对被控制、被否定或失去主动权保持警觉。",
    action: "带着防备进入协商，反复确认边界和对方意图。",
    need: "公平、可撤回的选择和不被羞辱的沟通。",
    stress: "会把合作谈成攻防，先证明自己没错再处理关系。",
    partnerMoves: ["避免贴标签和逼迫表态", "把选择与后果说清", "承认其合理顾虑"],
    selfMoves: ["区分风险与旧经验", "先提出目标再陈述防御", "给对方一次善意解释的机会"],
    similar: ["IVDP", "ITDR", "IVWR"],
  },
  {
    code: "IVDP",
    name: "防御掌舵者",
    group: "alert-space",
    tagline: "只要我先控制局面，就不会被动。",
    tendency: "防御型回避互动",
    summary: "对风险非常敏感，会通过控制节奏、规则或结论维持安全。",
    action: "抢先定义问题和边界，把可能的受伤转化成可控局面。",
    need: "自主权、尊重，以及不被突然侵入的安全感。",
    stress: "可能用冷硬决定替代协商，让对方只能接受或离开。",
    partnerMoves: ["保持语气稳定并守住底线", "不要参与权力拉扯", "只讨论可观察行为"],
    selfMoves: ["把命令改成边界与请求", "允许对方拥有不同解释", "注意控制是否正在制造更大风险"],
    similar: ["IVDR", "ITDP", "CVDP"],
  },
  {
    code: "IVWR",
    name: "推拉摆钟",
    group: "alert-space",
    tagline: "靠近会怕，离开也会怕。",
    tendency: "恐惧回避倾向",
    summary: "同时渴望连接和保护自己，容易在热烈靠近与突然降温之间摆动。",
    action: "确认安全时靠近，一感到暴露或失控就撤回。",
    need: "低压、稳定、可预测的连接经验。",
    stress: "会释放相反信号，让双方都难以判断真实意愿。",
    partnerMoves: ["保持稳定而非跟随冷热起伏", "尊重暂停但拒绝无限失联", "用小承诺建立可预测性"],
    selfMoves: ["命名自己正在害怕什么", "撤退前保留一句说明", "用小步靠近替代全有或全无"],
    similar: ["IVWP", "CVWR", "IVDR"],
  },
  {
    code: "IVWP",
    name: "警报孤岛",
    group: "alert-space",
    tagline: "先切断连接，至少不会继续受伤。",
    tendency: "高防御回避互动",
    summary: "面对不确定或冲突时优先封闭自己，把降低暴露看作最可靠的保护。",
    action: "停止表达、减少回应，从关系现场撤回到可控区域。",
    need: "不被追击的安全空间，以及不会惩罚脆弱的关系环境。",
    stress: "长期失联会让自保变成关系事实，也令修复成本持续上升。",
    partnerMoves: ["停止追逐式沟通", "留下一条清楚且有限的邀请", "为失联行为设置自己的边界"],
    selfMoves: ["用一句状态说明替代消失", "从低风险信息开始恢复联系", "必要时寻求专业支持而非独自承受"],
    similar: ["IVWR", "ITWP", "CVWP"],
  },
];

export function getTypeProfile(code: string) {
  return [
    { label: "亲密取向", value: code[0] === "C" ? "C 靠近" : "I 留白" },
    { label: "关系预期", value: code[1] === "T" ? "T 信任" : "V 警觉" },
    { label: "冲突动作", value: code[2] === "D" ? "D 直面" : "W 缓冲" },
    { label: "修复重心", value: code[3] === "R" ? "R 共建" : "P 自保" },
  ];
}
